# Environment: prod | Application: backend
image:
  repository: myregistry/backend
  tag: "3.4.1"

containerPort: 8080

# t-shirt size (or set custom `resources` to override)
resourceSize: xlarge

configMapRefs:
  backend-config: {}
  db-config: {}

secretRefs:
  backend-secrets: {}
  db-secrets: {}
