"""
Report generator - produces a structured markdown report from analysis results.
"""
import logging
import os
from datetime import datetime

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates a comprehensive markdown report from FoxPro analysis results."""

    def generate(self, results, extraction_stats, source_dir, output_path=None):
        """
        Generate the full analysis report.

        Args:
            results: list of AnalysisResult objects
            extraction_stats: dict with counts by type
            source_dir: path to the source directory analyzed
            output_path: optional output file path (default: auto-generated)

        Returns:
            Path to the generated report file.
        """
        if output_path is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = os.path.join(
                os.path.dirname(source_dir) if os.path.dirname(source_dir) else ".",
                f"foxpro_analysis_{timestamp}.md",
            )

        lines = []
        lines.extend(self._header(source_dir, extraction_stats))
        lines.extend(self._table_of_contents(results))
        lines.extend(self._detailed_analysis(results))
        lines.extend(self._appendix_python(results))

        content = "\n".join(lines)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

        logger.info("Report written to %s", output_path)
        return output_path

    def _header(self, source_dir, stats):
        """Generate report header with summary statistics."""
        lines = [
            "# FoxPro Application Analysis Report",
            "",
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Source Directory:** `{source_dir}`",
            f"**Analyzer:** vfp2py + Llama 3.1 (Ollama)",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
            "| Category | Count |",
            "|----------|-------|",
        ]

        for category, count in stats.items():
            lines.append(f"| {category} | {count} |")

        total = sum(stats.values())
        lines.append(f"| **Total Analyzed** | **{total}** |")
        lines.extend(["", "---", ""])
        return lines

    def _table_of_contents(self, results):
        """Generate table of contents grouped by source file."""
        lines = ["## Table of Contents", ""]

        current_file = ""
        for result in results:
            if result.source_file != current_file:
                current_file = result.source_file
                lines.append(f"### {current_file}")

            anchor = self._make_anchor(result.source_file, result.unit_name)
            icon = self._type_icon(result.unit_type)
            lines.append(f"- {icon} [{result.unit_type}: {result.unit_name}](#{anchor})")

        lines.extend(["", "---", ""])
        return lines

    def _detailed_analysis(self, results):
        """Generate detailed analysis sections."""
        lines = ["## Detailed Analysis", ""]

        current_file = ""
        for result in results:
            if result.source_file != current_file:
                current_file = result.source_file
                lines.extend([f"### {current_file}", ""])

            anchor = self._make_anchor(result.source_file, result.unit_name)
            icon = self._type_icon(result.unit_type)
            lines.extend([
                f'<a id="{anchor}"></a>',
                f"#### {icon} {result.unit_type}: {result.unit_name}",
                "",
                result.summary,
                "",
            ])

            # Show a snippet of the original code
            if result.original_code_snippet:
                lines.extend([
                    "<details>",
                    "<summary>View FoxPro Source (click to expand)</summary>",
                    "",
                    "```foxpro",
                    result.original_code_snippet[:2000],
                    "```",
                    "</details>",
                    "",
                ])

            lines.extend(["---", ""])

        return lines

    def _appendix_python(self, results):
        """Generate appendix with Python conversions (if available)."""
        has_python = any(r.python_equivalent for r in results)
        if not has_python:
            return []

        lines = [
            "## Appendix: Python Equivalents",
            "",
            "The following Python code was auto-generated by vfp2py. "
            "It provides a reference for understanding the FoxPro logic.",
            "",
        ]

        for result in results:
            if result.python_equivalent:
                lines.extend([
                    f"### {result.source_file} :: {result.unit_name}",
                    "",
                    "```python",
                    result.python_equivalent[:4000],
                    "```",
                    "",
                ])

        return lines

    def _make_anchor(self, source_file, unit_name):
        """Create a markdown-safe anchor ID."""
        text = f"{source_file}-{unit_name}"
        return "".join(c if c.isalnum() else "-" for c in text.lower())

    def _type_icon(self, unit_type):
        """Return a text marker for the unit type."""
        icons = {
            "MODULE": "[PRG]",
            "PROCEDURE": "[PROC]",
            "FUNCTION": "[FUNC]",
            "CLASS": "[CLS]",
            "MENU": "[MNU]",
            "FORM": "[FRM]",
            "PROJECT": "[PJX]",
        }
        return icons.get(unit_type, f"[{unit_type}]")
