spring:
  main:
    web-application-type: none
    banner-mode: off
    log-startup-info: false

migration:
  source:
    url: https://host.docker.internal:9043
    token: glpat-source-migration-test1
  destination:
    url: https://localhost:9044
    token: glpat-target-migration-test1
  source-url-for-import: https://gitlab:9043
  top-level-group: migration-test
  batch-size: 10
  sleep-between-batches-seconds: 5
  poll-interval-seconds: 10
  batch-timeout-seconds: 600
  state-file: transfer_state.json
  reports-dir: reports
  ssl:
    truststore-path: gitlab-trust.jks
    truststore-password: changeit
    truststore-type: PKCS12
    skip-hostname-verification: true
