package com.example.rag.rest.dto;

import java.util.List;

/**
 * Response DTO for query endpoint.
 * Contains the answer generated by the RAG system along with source chunks used.
 */
public record QueryResponse(
    boolean success,
    String question,
    String answer,
    List<SourceMetadata> sources,
    String errorMessage
) {
    /**
     * Creates a successful query response.
     */
    public static QueryResponse success(String question, String answer, List<SourceMetadata> sources) {
        return new QueryResponse(
            true,
            question,
            answer,
            sources,
            null
        );
    }

    /**
     * Creates an error response.
     */
    public static QueryResponse error(String question, String errorMessage) {
        return new QueryResponse(
            false,
            question,
            null,
            List.of(),
            errorMessage
        );
    }
}
