# =============================================================================
# Dev environment overrides
# =============================================================================
replicaCount: 1

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

route:
  host: hello-dev.apps.ocp.example.com

config:
  appEnvironment: dev
