# Environment: dev | Application: frontend
image:
  repository: myregistry/frontend
  tag: "dev-latest"

containerPort: 3000

service:
  port: 3000

configMapRefs:
  frontend-config: {}

secretRefs:
  frontend-secrets: {}
