apiVersion: v1
kind: Namespace
metadata:
  name: conjur-system
  labels:
    purpose: secrets-management
---
apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    purpose: data-tier
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    purpose: ci-cd
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    purpose: application-tier
