apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  APP_NAME: {{ .Values.config.appName | quote }}
  APP_ENVIRONMENT: {{ .Values.config.appEnvironment | quote }}
  APP_VERSION: {{ .Values.config.appVersion | quote }}
