# MicroProfile REST Client configuration for conjur-microprofile-rest service
conjur-api/mp-rest/url=http://conjur-rest.apps.svc.cluster.local:9080
conjur-api/mp-rest/connectTimeout=5000
conjur-api/mp-rest/readTimeout=10000
